/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.0.0
 *
 * Project: 'HSE_LSE_SYS32Mhz_SPI' 
 * Target:  'HSE_LSE_SYS32Mhz_SPI' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32wbxx.h"



#endif /* RTE_COMPONENTS_H */
